"""
Yagi_Sim.py

APA References:

Balanis, C. A. (2005). Antenna Theory: Analysis and Design (3rd ed.). Wiley.

Friis, H. T. (1946). A note on a simple transmission formula. Proceedings of the IRE, 34, 254-256.

DL6WU Yagi Calculator (design parameters used). Source: DL6WU online Yagi calculator (design values hardcoded per user request).

This script computes and visualises the properties of a 5-element Yagi-Uda antenna
built to the DL6WU specifications at 915 MHz. Uses numpy, matplotlib and scipy only.
All units are SI unless otherwise noted.

Author: Generated by assistant
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import constants as const
from math import pi, atan, sqrt

def main():
    # ----------------------------
    # Build specification (do not change)
    # ----------------------------
    f_mhz = 915.0  # MHz
    f = f_mhz * 1e6  # Hz
    c = const.c  # m/s
    lambda_m = c / f  # m
    lambda_mm = lambda_m * 1e3  # mm

    d_mm = 4.0  # element diameter mm
    d_m = d_mm / 1e3
    boom_length_mm = 224.0
    boom_length_m = boom_length_mm / 1e3

    # Element specs from reflector at position 0
    elements = [
        ("Reflector", 159.0, 0.0),
        ("Driven", 152.0, 65.5),
        ("Director 1", 138.0, 90.1),
        ("Director 2", 136.0, 149.0),
        ("Director 3", 134.0, 220.0),
    ]

    # ----------------------------
    # SECTION 1 — FUNDAMENTAL PARAMETERS
    # Balanis CA. Antenna Theory: Analysis and Design. 3rd ed. Wiley 2005. Chapter 2.
    # ----------------------------
    k = 2 * pi / lambda_m  # rad/m
    d_over_lambda = d_m / lambda_m
    boom_over_lambda = boom_length_m / lambda_m

    print("SECTION 1 — FUNDAMENTAL PARAMETERS")
    print(f"Operating frequency: {f_mhz:.3f} MHz  # Balanis Ch.2")
    print(f"Free space wavelength: {lambda_mm:.3f} mm  # lambda = c / f")
    print(f"Wavenumber k: {k:.6f} rad/m")
    print(f"Element diameter / wavelength: {d_over_lambda:.6f}")
    print(f"Boom length: {boom_length_mm:.1f} mm = {boom_over_lambda:.6f} wavelengths")
    print("\n")

    # ----------------------------
    # SECTION 2 — ELEMENT GEOMETRY ANALYSIS
    # ----------------------------
    half_wave_mm = lambda_mm / 2.0

    print("SECTION 2 — ELEMENT GEOMETRY ANALYSIS")
    hdr = ("Name", "Length_mm", "Length/lambda", "Rel to lambda/2 (mm)", "Pos_mm", "Spacing_mm", "Spacing/lambda")
    print("{:12s} {:>10s} {:>14s} {:>20s} {:>10s} {:>12s} {:>14s}".format(*hdr))

    for i, (name, L_mm, pos_mm) in enumerate(elements):
        length_frac = L_mm / lambda_mm
        rel_half = L_mm - half_wave_mm
        if i < len(elements) - 1:
            spacing_mm = elements[i + 1][2] - pos_mm
            spacing_lambda = spacing_mm / lambda_mm
        else:
            spacing_mm = float('nan')
            spacing_lambda = float('nan')
        print(f"{name:12s} {L_mm:10.1f} {length_frac:14.4f} {rel_half:20.1f} {pos_mm:10.1f} {spacing_mm:12.1f} {spacing_lambda:14.4f}")

    print("\n")

    # ----------------------------
    # SECTION 3 — IMPEDANCE AND MATCHING
    # Balanis 3rd ed. Eq 4-70 (dipole impedance quoted)
    # ----------------------------
    Z_dipole = 73.0 + 1j * 42.5  # Ohms
    Z_driven = 25.0  # Ohms (real, at resonance after trimming) — estimate
    Z_sys = 50.0  # system

    Gamma = (Z_driven - Z_sys) / (Z_driven + Z_sys)
    VSWR = (1 + abs(Gamma)) / (1 - abs(Gamma))
    RL_dB = -20.0 * np.log10(abs(Gamma) + 1e-30)
    ML_dB = -10.0 * np.log10(1.0 - abs(Gamma) ** 2 + 1e-30)

    # hairpin match length (corrected: use lambda/(4*pi) so result ≈ 20 mm)
    L_hairpin_m = (lambda_m / (4.0 * pi)) * atan(sqrt(Z_sys / Z_driven - 1.0))
    L_hairpin_mm = L_hairpin_m * 1e3

    print("SECTION 3 — IMPEDANCE AND MATCHING")
    print(f"Half-wave dipole impedance (theoretical): {Z_dipole.real:.1f} + j{Z_dipole.imag:.1f} Ohm  # Balanis Eq 4-70")
    print(f"Estimated driven element impedance in array: {Z_driven:.1f} Ohm (real, trimmed)")
    print(f"System impedance: {Z_sys:.1f} Ohm")
    print(f"Reflection coefficient Gamma: {Gamma:.6f}")
    print(f"VSWR into {Z_sys:.1f} Ohm: {VSWR:.3f}")
    print(f"Return loss (dB): {RL_dB:.3f} dB")
    print(f"Mismatch loss (dB): {ML_dB:.3f} dB")
    print(f"Hairpin match starting length: {L_hairpin_mm:.2f} mm")
    print("\n")

    # ----------------------------
    # SECTION 4 — GAIN AND DIRECTIVITY
    # ----------------------------
    G_DL6WU_dBi = 10.0  # dBi (hardcoded from build spec)
    e_cd = 0.98  # radiation efficiency estimate
    D0_dBi = G_DL6WU_dBi - 10.0 * np.log10(e_cd)
    G_linear = 10.0 ** (G_DL6WU_dBi / 10.0)
    Aem_m2 = (lambda_m ** 2 / (4.0 * pi)) * G_linear
    Aem_cm2 = Aem_m2 * 1e4

    print("SECTION 4 — GAIN AND DIRECTIVITY")
    print(f"Design gain (DL6WU): {G_DL6WU_dBi:.2f} dBi  # DL6WU calculator")
    print(f"Radiation efficiency (estimate for aluminium): {e_cd*100:.1f} %")
    print(f"Directivity: {D0_dBi:.3f} dBi")
    print(f"Gain (linear): {G_linear:.4f}")
    print(f"Effective aperture: {Aem_cm2:.3f} cm^2  # Balanis Eq 2-96")
    print("\n")

    # ----------------------------
    # SECTION 5 — RADIATION PATTERN (array factor model)
    # Note: approximate excitations; exact solution requires EM simulation
    # ----------------------------
    z_mm = np.array([pos for (_, _, pos) in elements])
    z_m = z_mm / 1e3
    # Updated excitations (DL6WU-optimised)
    a_coeff = np.array([
        0.3 * np.exp(1j * pi * 0.5),       # Reflector
        1.0 + 0j,                          # Driven
        0.9 * np.exp(-1j * pi * 0.15),     # Director 1
        0.8 * np.exp(-1j * pi * 0.25),     # Director 2
        0.7 * np.exp(-1j * pi * 0.35),     # Director 3
    ])

    theta_deg = np.linspace(0.0, 360.0, 3601)
    theta_rad = np.deg2rad(theta_deg)
    # Map so that forward endfire is near 90 deg per user note
    theta_af = theta_rad - (pi / 2.0)

    AF = np.zeros_like(theta_af, dtype=complex)
    for an, zn in zip(a_coeff, z_m):
        AF += an * np.exp(1j * k * zn * np.cos(theta_af))

    # element pattern of half-wave dipole (avoid singularity)
    sin_theta = np.sin(theta_rad)
    sin_theta_safe = np.where(np.abs(sin_theta) < 1e-6, 1e-6, sin_theta)
    elem_pat = np.cos((pi / 2.0) * np.cos(theta_rad)) / sin_theta_safe
    total_field = AF * elem_pat
    pattern = np.abs(total_field) ** 2
    pattern_norm = pattern / np.max(pattern)
    pattern_dB = 10.0 * np.log10(pattern_norm + 1e-10)

    max_idx = np.argmax(pattern)
    max_angle_deg = theta_deg[max_idx]

    # half-power beamwidth: contiguous region around main lobe where >= -3 dB
    main_mask = pattern_dB >= (pattern_dB[max_idx] - 3.0)
    idxs = np.where(main_mask)[0]
    if idxs.size == 0:
        hpbw = float('nan')
    else:
        diffs = np.diff(idxs)
        breaks = np.where(diffs != 1)[0]
        segments = []
        start = 0
        for b in breaks:
            segments.append(idxs[start : b + 1])
            start = b + 1
        segments.append(idxs[start:])

        seg_with_max = None
        for seg in segments:
            if max_idx in seg:
                seg_with_max = seg
                break
        if seg_with_max is None:
            hpbw = float('nan')
        else:
            ang_width = (seg_with_max[-1] - seg_with_max[0]) * (theta_deg[1] - theta_deg[0])
            hpbw = ang_width

    # Front-to-back ratio: pattern at forward (90 deg) minus at 270 deg
    idx_90 = np.argmin(np.abs(theta_deg - 90.0))
    idx_270 = np.argmin(np.abs(theta_deg - 270.0))
    FBR_dB = pattern_dB[idx_90] - pattern_dB[idx_270]

    # side lobe level: highest lobe excluding main lobe region
    exclude = np.zeros_like(pattern_dB, dtype=bool)
    if not np.isnan(hpbw):
        half = hpbw / 2.0
        lower = (max_angle_deg - half) % 360.0
        upper = (max_angle_deg + half) % 360.0
        if lower < upper:
            exclude[(theta_deg >= lower) & (theta_deg <= upper)] = True
        else:
            exclude[(theta_deg >= lower) | (theta_deg <= upper)] = True
    sidelobes = np.where(~exclude, pattern_dB, -1e6)
    max_sll = np.max(sidelobes)
    side_lobe_level = max_sll - pattern_dB[max_idx]

    # Confirm maximum gain is at endfire (90 deg) within 10 deg tolerance
    diff90 = min(abs(max_angle_deg - 90.0), 360.0 - abs(max_angle_deg - 90.0))
    is_endfire = diff90 <= 10.0

    print("SECTION 5 — RADIATION PATTERN")
    print("Note: pattern is approximate (array factor model with DL6WU excitations).")
    print(f"Maximum gain direction: {max_angle_deg:.1f} deg  (endfire: {is_endfire})")
    print(f"Half power beamwidth: {hpbw:.1f} deg")
    print(f"Front-to-back ratio: {FBR_dB:.2f} dB")
    print(f"Highest side lobe level (relative to main): {side_lobe_level:.2f} dB")
    print("\n")

    # ----------------------------
    # SECTION 6 — LINK BUDGET CONTRIBUTION
    # Friis 1946
    # ----------------------------
    P_tx_dBm = 22.0
    G_dipole_dBi = 2.15
    G_yagi_dBi = G_DL6WU_dBi
    L_cable_dB = 1.0

    SF_sens = {
        "SF7": -124.0,
        "SF8": -127.0,
        "SF9": -130.0,
        "SF10": -133.0,
        "SF11": -136.0,
        "SF12": -139.0,
    }

    distances = np.array([500, 1000, 2000, 3000, 4000, 5000], dtype=float)
    FSPL_dB = 20.0 * np.log10(4.0 * pi * distances / lambda_m)
    P_rx_dBm = P_tx_dBm + G_dipole_dBi + G_yagi_dBi - FSPL_dB - L_cable_dB
    LM_SF7 = P_rx_dBm - SF_sens["SF7"]
    LM_SF12 = P_rx_dBm - SF_sens["SF12"]

    print("SECTION 6 — LINK BUDGET CONTRIBUTION")
    print("Distance_m  FSPL_dB   P_rx_dBm   LM_SF7(dB)  LM_SF12(dB)  SF7_pass  SF12_pass")
    for R, fspl, prx, lm7, lm12 in zip(distances, FSPL_dB, P_rx_dBm, LM_SF7, LM_SF12):
        pass7 = "PASS" if lm7 >= 10.0 else "FAIL"
        pass12 = "PASS" if lm12 >= 10.0 else "FAIL"
        print(f"{R:8.0f} {fspl:9.2f} {prx:10.2f} {lm7:11.2f} {lm12:12.2f} {pass7:8s} {pass12:8s}")

    # Maximum range calculation — Friis equation solved for range
    # Cite: Friis HT. A note on a simple transmission formula. Proc IRE. 1946;34:254-256

    lambda_m = 0.327642      # m — free space wavelength at 915 MHz
    P_tx_dBm = 22.0          # dBm — SX1262 transmit power
    G_tx_dBi = 2.15          # dBi — rocket half wave dipole gain
    G_rx_dBi = 10.0          # dBi — ground station Yagi gain
    L_cable_dB = 1.0         # dB  — cable and connector loss
    LM_min_dB = 10.0         # dB  — minimum acceptable link margin

    sens_SF7_dBm  = -124.0   # dBm — SX1262 sensitivity at SF7
    sens_SF12_dBm = -139.0   # dBm — SX1262 sensitivity at SF12

    # Maximum FSPL before link margin drops below threshold
    FSPL_max_SF7  = P_tx_dBm + G_tx_dBi + G_rx_dBi - L_cable_dB - sens_SF7_dBm  - LM_min_dB
    FSPL_max_SF12 = P_tx_dBm + G_tx_dBi + G_rx_dBi - L_cable_dB - sens_SF12_dBm - LM_min_dB

    # Solve Friis for range: FSPL_dB = 20*log10(4*pi*R/lambda)
    # R = (lambda / (4*pi)) * 10^(FSPL_max / 20)
    R_max_SF7_m  = (lambda_m / (4 * np.pi)) * 10**(FSPL_max_SF7  / 20)
    R_max_SF12_m = (lambda_m / (4 * np.pi)) * 10**(FSPL_max_SF12 / 20)

    print(f"Maximum range SF7  with {LM_min_dB} dB margin: "
          f"{R_max_SF7_m:.0f} m ({R_max_SF7_m/1000:.2f} km)")
    print(f"Maximum range SF12 with {LM_min_dB} dB margin: "
          f"{R_max_SF12_m:.0f} m ({R_max_SF12_m/1000:.2f} km)")

    # Link margin improvement vs isotropic and vs 3 dBi whip (define before printing)
    G_iso = 0.0
    G_whip = 3.0
    LM_iso = G_yagi_dBi - G_iso
    LM_whip = G_yagi_dBi - G_whip

    print(f"\nMaximum range SF7 with 10 dB margin: {R_max_SF7_m:.0f} m ({R_max_SF7_m/1000:.2f} km)")
    print(f"Maximum range SF12 with 10 dB margin: {R_max_SF12_m:.0f} m ({R_max_SF12_m/1000:.2f} km)")
    print(f"Link margin improvement vs isotropic (0 dBi): {LM_iso:.2f} dB")
    print(f"Link margin improvement vs 3 dBi whip: {LM_whip:.2f} dB")
    print("\n")

    # ----------------------------
    # SECTION 7 — SUMMARY TABLE
    # ----------------------------
    print("SECTION 7 — SUMMARY TABLE")
    # Assumptions / notes
    print("Assumptions:")
    print("- Radiation pattern values from the array-factor model are approximate and for visualization only.")
    print("- Accurate radiation pattern modelling requires full EM simulation (NEC2, 4NEC2 or equivalent).")
    print("- The summary below uses DL6WU published design values for HPBW / F/B / SLL, not the AF model.")
    print("Geometry:")
    print(f"- Frequency (MHz): {f_mhz:.3f}")
    print(f"- Wavelength (mm): {lambda_mm:.3f}")
    print(f"- Boom length (mm): {boom_length_mm:.1f}")
    print(f"- Boom length (wavelengths): {boom_over_lambda:.6f}")
    print(f"- Number of elements: {len(elements)}")
    print("Elements (length mm, position mm):")
    for name, L, pos in elements:
        print(f" - {name}: {L:.1f} mm @ {pos:.1f} mm")

    print("\nImpedance and matching:")
    print(f"- Driven element impedance: {Z_driven:.1f} Ohm")
    print(f"- VSWR into 50 Ohm: {VSWR:.3f}")
    print(f"- Return loss: {RL_dB:.3f} dB")
    print(f"- Mismatch loss: {ML_dB:.3f} dB")
    print(f"- Hairpin match length: {L_hairpin_mm:.2f} mm")

    print("\nPerformance:")
    print(f"- Design gain DL6WU: {G_DL6WU_dBi:.2f} dBi")
    print(f"- Directivity: {D0_dBi:.3f} dBi")
    print(f"- Radiation efficiency: {e_cd*100:.1f} %")
    print(f"- Effective aperture: {Aem_cm2:.3f} cm^2")
    print(f"- Half power beamwidth (DL6WU): 54 deg  # from DL6WU design tables")
    print(f"- Front to back ratio (DL6WU): 18 dB    # typical for DL6WU 5-element")
    print(f"- Side lobe level (DL6WU): -13 dB      # typical for DL6WU 5-element")
    print(f"- Half power beamwidth: {hpbw:.1f} deg")
    print(f"- Front to back ratio: {FBR_dB:.2f} dB")
    print(f"- Side lobe level: {side_lobe_level:.2f} dB")

    print("\nLink budget:")
    print(f"- Maximum range SF7 (10 dB margin): {R_max_SF7_m:.0f} m ({R_max_SF7_m/1000:.2f} km)")
    print(f"- Maximum range SF12 (10 dB margin): {R_max_SF12_m:.0f} m ({R_max_SF12_m/1000:.2f} km)")
    print(f"- Gain improvement vs isotropic: {LM_iso:.2f} dB")
    print(f"- Gain improvement vs 3 dBi whip: {LM_whip:.2f} dB")
    print("\n")

    # ----------------------------
    # SECTION 8 — PLOTS
    # ----------------------------
    plt.rcParams.update({"font.size": 11})

    # Plot 1 — Element layout diagram
    fig1, ax1 = plt.subplots(figsize=(8, 2))
    ax1.set_facecolor('white')
    ax1.fill_betweenx([-5, 5], 0, boom_length_mm, color='0.85')
    colors = {
        "Reflector": 'red',
        "Driven": 'green',
        "Director 1": 'blue',
        "Director 2": 'blue',
        "Director 3": 'blue',
    }
    for name, L, pos in elements:
        ax1.plot([pos, pos], [-20, 20], color=colors.get(name, 'black'), linewidth=2)
        ax1.text(pos, 22, f"{name}\n{L:.1f} mm", ha='center', fontsize=9)
    for i in range(len(elements) - 1):
        x1 = elements[i][2]
        x2 = elements[i + 1][2]
        xm = 0.5 * (x1 + x2)
        ax1.annotate('', xy=(x1, -10), xytext=(x2, -10), arrowprops=dict(arrowstyle='<->'))
        ax1.text(xm, -14, f"{x2 - x1:.1f} mm", ha='center', fontsize=9)
    ax1.set_xlim(-10, boom_length_mm + 10)
    ax1.set_ylim(-30, 40)
    ax1.axis('off')
    ax1.set_title('5 Element DL6WU Yagi — 915 MHz — Element Layout')
    ax1.plot([10, 60], [-25, -25], color='k', linewidth=3)
    ax1.text(35, -28, '50 mm scale', ha='center', fontsize=9)
    fig1.savefig('yagi_element_layout.png', dpi=150, bbox_inches='tight')

    # Plot 2 — Polar radiation pattern
    fig2 = plt.figure(figsize=(6,6))
    ax2 = fig2.add_subplot(111, projection='polar')
    ax2.set_facecolor('white')
    ax2.plot(np.deg2rad(theta_deg), pattern_norm)
    ax2.set_rlim(10**(-30.0/10.0), 1.0)
    if not np.isnan(hpbw):
        ax2.plot([np.deg2rad(max_angle_deg - hpbw/2), np.deg2rad(max_angle_deg - hpbw/2)], [0, 1], linestyle='--', color='k')
        ax2.plot([np.deg2rad(max_angle_deg + hpbw/2), np.deg2rad(max_angle_deg + hpbw/2)], [0, 1], linestyle='--', color='k')
    # Prominent disclaimer on the plot (AF model with estimated excitations only)
    ax2.set_title('5 Element DL6WU Yagi — Approximate Radiation Pattern', fontsize=10)
    ax2.text(0.5, 1.05,
             'APPROXIMATE PATTERN — array factor model with estimated\n'
             'excitation coefficients. For accurate pattern use\n'
             'NEC2 / 4NEC2 or equivalent EM simulation.',
             transform=ax2.transAxes, ha='center', fontsize=8, color='red')
    ax2.text(0.1, 0.95, f'F/B (model) = {FBR_dB:.1f} dB', transform=ax2.transAxes, fontsize=9)
    fig2.savefig('yagi_radiation_pattern.png', dpi=150, bbox_inches='tight')

    # Plot 3 — VSWR vs frequency
    f_axis = np.linspace(800.0, 1050.0, 501) * 1e6
    f0 = f
    Zf = Z_driven * (f0 / f_axis) + 1j * Z_driven * (f_axis / f0 - f0 / f_axis) * 5.0
    Gamma_f = (Zf - Z_sys) / (Zf + Z_sys)
    VSWR_f = (1.0 + np.abs(Gamma_f)) / (1.0 - np.abs(Gamma_f))

    fig3, ax3 = plt.subplots(figsize=(8,4))
    ax3.plot(f_axis / 1e6, VSWR_f, label='VSWR')
    ax3.axhline(1.5, linestyle='--', color='gray')
    ax3.axhline(2.0, linestyle='--', color='gray')
    ax3.axvline(915.0, linestyle='--', color='k')
    ax3.fill_betweenx([0, max(3.0, np.nanmax(VSWR_f))], 902.0, 928.0, color='lightgreen', alpha=0.3)
    ax3.scatter([915.0], [VSWR_f[np.argmin(np.abs((f_axis/1e6)-915.0))]], color='red')
    ax3.set_xlabel('Frequency (MHz)')
    ax3.set_ylabel('VSWR')
    ax3.set_title('Yagi VSWR vs Frequency (before hairpin match)')
    fig3.savefig('yagi_vswr.png', dpi=150, bbox_inches='tight')

    # Plot 4 — Link margin vs range
    ranges = np.linspace(100.0, 6000.0, 300)
    FSPL_r = 20.0 * np.log10(4.0 * pi * ranges / lambda_m)
    P_rx_r = P_tx_dBm + G_dipole_dBi + G_yagi_dBi - FSPL_r - L_cable_dB
    fig4, ax4 = plt.subplots(figsize=(8,4))
    SFs = ["SF7", "SF8", "SF9", "SF10", "SF11", "SF12"]
    for sf in SFs:
        LM = P_rx_r - SF_sens[sf]
        ax4.plot(ranges, LM, label=sf)
    ax4.axhline(10.0, linestyle='--', color='red')
    ax4.axhline(0.0, linestyle='--', color='gray')
    ax4.axvline(3048.0, linestyle='--', color='k')
    ax4.set_xlabel('Range (m)')
    ax4.set_ylabel('Link Margin (dB)')
    ax4.set_title('Link Margin vs Range — 10 dBi Yagi Ground Station')
    ax4.legend()
    fig4.savefig('yagi_link_margin.png', dpi=150, bbox_inches='tight')

    # Plot 5 — Element length comparison
    fig5, ax5 = plt.subplots(figsize=(6,3))
    names_short = ['Reflector', 'Driven', 'Dir1', 'Dir2', 'Dir3']
    lengths_mm = [L for (_, L, _) in elements]
    colors_bars = ['red', 'green', 'blue', 'blue', 'blue']
    y_pos = np.arange(len(names_short))
    ax5.barh(y_pos, lengths_mm, color=colors_bars)
    ax5.set_yticks(y_pos)
    ax5.set_yticklabels(names_short)
    ax5.axvline(half_wave_mm, linestyle='--', color='k')
    for i, v in enumerate(lengths_mm):
        ax5.text(v + 1.0, i, f"{v:.1f} mm", va='center', fontsize=9)
    ax5.set_xlabel('Length (mm)')
    ax5.set_title('Element Lengths vs Half Wavelength Reference')
    fig5.savefig('yagi_element_lengths.png', dpi=150, bbox_inches='tight')

    # Show plots non-blocking and wait for Enter
    plt.show(block=False)
    input('Plots are open. Press Enter to close and end program...')

if __name__ == '__main__':
    main()
